### ISSUE TITLE
Workshop Hands on Lab Guide Improvements

### ISSUE THREAD

**Issue by AJLab-GH** [FortinetCloudCSE/k8s-101-workshop#71]
The script used in "Quick AKS Cluster Setup" in "K8s Basic" feature the wrong value for the FortiLab key (tag). This causes the resourcegroupname variable to be return an empty value, and fail the "az aks create" command.

```text
##generate public key if not exist 
[ ! -f ~/.ssh/id_rsa ] && ssh-keygen -q -N "" -f ~/.ssh/id_rsa
clustername=$(whoami)

##get the resourcegrname name 
resourcegroupname=$(az group list --tag FortiLab="k8s101-lab" | jq -r .[].name)
az aks create \
    --name ${clustername} \
    --node-count 1 \
    --vm-set-type VirtualMachineScaleSets \
    --network-plugin azure \
    --service-cidr  10.96.0.0/16 \
    --dns-service-ip 10.96.0.10 \
    --nodepool-name worker \
    --resource-group $resourcegroupname

##update kubeconfig file for kubectl to use 
az aks get-credentials -g  $resourcegroupname -n ${clustername} --overwrite-existing
```

The same behaviour exists in "Node and Service" when running the "az aks delete" command.

The current value for FortiLab is = azure-k8s-seintro-110

**Comment by yagosys** [comment]
thanks. fixed  by remove the tag.  instead use resourcegroupname=$(az group list | jq -r .[0].name)  .
